apiVersion: v1
kind: Namespace
metadata:
  name: netpol-test-circle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: circle-app-1
  namespace: netpol-test-circle
  labels:
    app: circle-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circle-app-1
  template:
    metadata:
      labels:
        app: circle-app-1
    spec:
      containers:
      - name: circle-app-1
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: circle-app-2
  namespace: netpol-test-circle
  labels:
    app: circle-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circle-app-2
  template:
    metadata:
      labels:
        app: circle-app-2
    spec:
      containers:
      - name: circle-app-2
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: circle-app-1
  namespace: netpol-test-circle
spec:
  ports:
    - name: service
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: circle-app-1
---
apiVersion: v1
kind: Service
metadata:
  name: circle-app-2
  namespace: netpol-test-circle
spec:
  ports:
    - name: service
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: circle-app-2
