apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-ingress-allow-egress
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}  # Allowing ingress from all pods in the same namespace
  egress:
  - to:
    - namespaceSelector: {}  # Allowing egress to all namespaces
